### PR TITLE
run all test

### PR DESCRIPTION
**Pull request by Alfredbis29**
In this milestone of project We:

set up React Testing Library.
Write unit tests for the files operate.js and calculate.js using Jest.
Create unit tests for all React components:
Use Jest snapshots to test the components.
Use React Testing Library to simulate user interaction.

### CODE REVIEW

**Comment by Alfredbis29** [comment]
**In this milestone of project We:**

- set up React Testing Library.
- Write unit tests for the files operate.js and calculate.js using Jest.
- Create unit tests for all React components:
- Use Jest snapshots to test the components.
- Use React Testing Library to simulate user interaction.

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi @Alfredbis29 ,  

Your project is complete! Great job for nailing it right on the first attempt 🥇

giphy

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alfredbis29** [comment]
Thanks so much @ShoiraTa  for your professional review

**Comment by ShoiraTa** [comment]
Hey, @Alfredbis29 
Can you update the Rull request and add description ?

**Comment by ShoiraTa** [comment]
First I approved then noticed that the PR has no description 🙈

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi @Alfredbis29 ,  

Your project is complete! Great job for nailing it right on the first attempt 🥇  🎉💯🌟 


giphy

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ShoiraTa** [comment]
@Alfredbis29 , good job 👍🏻

**Comment by Alfredbis29** [comment]
Alright ! thanks for the code review

**Pull request merged**
